tables:
order:
max_ctx_dim: 500
default_args:
  synthesize: true
  # Whether this table need to be synthesized. If set to false, it can mean a table that can output the exact same table
  # as real one, especially for very small tables and tables without any privacy concern, such as the products table for
  # a transaction database, if one wants to get real productions generated.
  standalone:  # arguments for standalone tabular model
    epochs: 20
    batch_size: 500
  degree: {}  # arguments for degree model
table_specific_args:
  appearances:
