tables:
  parent:
    name: parent
    id_columns:
      - id
    primary_key: id
  parent2:
    name: parent2
    id_columns:
      - id
    primary_key: id
  child:
    name: child
    id_columns:
      - id
      - parent_id
    primary_key:
      - id
      - parent_id
    sortby: id
    foreign_keys:
      - child_table_name: child
        parent_table_name: parent
        child_column_names: parent_id
        parent_column_names: id
  child2:
    name: child2
    id_columns:
      - id
      - parent_id
      - parent_id2
    primary_key: id
    foreign_keys:
      - child_table_name: child2
        parent_table_name: parent
        child_column_names: parent_id
        parent_column_names: id
      - child_table_name: child2
        parent_table_name: parent2
        child_column_names: parent_id2
        parent_column_names: id
order:
  - parent
  - parent2
  - child
  - child2
max_ctx_dim: 5
default_args:
  synthesize: true
  # Whether this table need to be synthesized. If set to false, it can mean a table that can output the exact same table
  # as real one, especially for very small tables and tables without any privacy concern, such as the products table for
  # a transaction database, if one wants to get real productions generated.
  standalone:  # arguments for standalone tabular model
    epochs: 20
    batch_size: 500
  degree: {}  # arguments for degree model (all FKs in the table if under table-specific)
  isna: {} # arguments for is-N/A indicator model (all FKs in the table if under table-specific)
  aggregated:
    # arguments for multi-variate potentially-continuous conditional tabular data generation for aggregated
    # information generation.
    epochs: 20
    batch_size: 500
  actual:
    # arguments for multi-variate sequential data based on static context and known lengths generation for generating
    # actual values.
    epochs: 20
    batch_size: 500
table_specific_args:  # these will override default if new arguments are provided.
  parent:
    synthesize: false
  child:
    actual:
      batch_size: 100
